### ISSUE TITLE
Editor type broke in 1.1.0

### ISSUE THREAD

**Issue by NomarCub** [Fevol/obsidian-typings#50]
This line used to compile with 1.0.8, but it fails with 1.1.0 and 1.1.1: https://github.com/NomarCub/obsidian-copy-url-in-preview/blob/8585e03c07b15f8617b1d433236645820b22cfcd/src/main.ts#L115.
tsc emits this error: `Property 'getClickableTokenAt' does not exist on type 'Editor'`.
It might be a user error on my part, in which case I'd appreciate any help or pointers too.

**Comment by Fevol** [comment]
Yeah sorry, that is my bad. The `Editor` class is exposed in the obsidian module as `hm`, but it is extended by a class `RO` which actually adds the `getClickableTokenAt` method, among other things. `hm` doesn't seem to be used anywhere else, other than being extended by `RO`, so I changed `hm` to be `BaseEditor`, and `RO` as the `Editor`. That should fix most things.

(Release coming asap)

**Comment by Fevol** [comment]
Let me know if release 1.1.2 fixes the issue (and/or breaks other things)

**Comment by NomarCub** [comment]
It works, thank you for the fast response!
